{-# OPTIONS_GHC -fno-warn-incomplete-patterns #-}
module PrintRomeo where

-- pretty-printer generated by the BNF converter

import AbsRomeo
import Data.Char


-- the top-level printing method
printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 (map ($ "") $ d []) "" where
  rend i ss = case ss of
    "["      :ts -> showChar '[' . rend i ts
    "("      :ts -> showChar '(' . rend i ts
    "{"      :ts -> showChar '{' . new (i+1) . rend (i+1) ts
    "}" : ";":ts -> new (i-1) . space "}" . showChar ';' . new (i-1) . rend (i-1) ts
    "}"      :ts -> new (i-1) . showChar '}' . new (i-1) . rend (i-1) ts
    ";"      :ts -> showChar ';' . new i . rend i ts
    t  : "," :ts -> showString t . space "," . rend i ts
    t  : ")" :ts -> showString t . showChar ')' . rend i ts
    t  : "]" :ts -> showString t . showChar ']' . rend i ts
    t        :ts -> space t . rend i ts
    _            -> id
  new i   = showChar '\n' . replicateS (2*i) (showChar ' ') . dropWhile isSpace
  space t = showString t . (\s -> if null s then "" else (' ':s))

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- the printer class does the job
class Print a where
  prt :: Int -> a -> Doc
  prtList :: Int -> [a] -> Doc
  prtList i = concatD . map (prt i)

instance Print a => Print [a] where
  prt = prtList

instance Print Char where
  prt _ s = doc (showChar '\'' . mkEsc '\'' s . showChar '\'')
  prtList _ s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q s = case s of
  _ | s == q -> showChar '\\' . showChar s
  '\\'-> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  _ -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j<i then parenth else id


instance Print Integer where
  prt _ x = doc (shows x)


instance Print Double where
  prt _ x = doc (shows x)


instance Print Ident where
  prt _ (Ident i) = doc (showString ( i))
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])


instance Print (Program a) where
  prt i e = case e of
    Prog _ stmts -> prPrec i 0 (concatD [prt 0 stmts])

instance Print (Stmt a) where
  prt i e = case e of
    Empty _ -> prPrec i 0 (concatD [doc (showString ";")])
    Ass _ id asg expr -> prPrec i 0 (concatD [prt 0 id, prt 0 asg, prt 0 expr, doc (showString ";")])
    Cond _ expr stmts elifs -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 stmts, prt 0 elifs, doc (showString "end")])
    CondElse _ expr stmts1 elifs stmts2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 expr, prt 0 stmts1, prt 0 elifs, doc (showString "else"), prt 0 stmts2, doc (showString "end")])
    While _ expr stmts -> prPrec i 0 (concatD [doc (showString "while"), prt 0 expr, prt 0 stmts, doc (showString "end")])
    For _ id expr1 expr2 stmts -> prPrec i 0 (concatD [doc (showString "for"), prt 0 id, doc (showString "="), prt 0 expr1, doc (showString ":"), prt 0 expr2, prt 0 stmts, doc (showString "end")])
    ForIn _ id1 id2 stmts -> prPrec i 0 (concatD [doc (showString "for"), prt 0 id1, doc (showString "in"), prt 0 id2, prt 0 stmts, doc (showString "end")])
    Break _ -> prPrec i 0 (concatD [doc (showString "break"), doc (showString ";")])
    Cont _ -> prPrec i 0 (concatD [doc (showString "continue"), doc (showString ";")])
    Func _ id ids stmts -> prPrec i 0 (concatD [doc (showString "function"), prt 0 id, doc (showString "("), prt 0 ids, doc (showString ")"), prt 0 stmts, doc (showString "end")])
    Ret _ expr -> prPrec i 0 (concatD [doc (showString "return"), prt 0 expr, doc (showString ";")])
    VRet _ -> prPrec i 0 (concatD [doc (showString "return"), doc (showString ";")])
    Yeld _ expr -> prPrec i 0 (concatD [doc (showString "Yield"), prt 0 expr, doc (showString ";")])
    Print _ expr -> prPrec i 0 (concatD [doc (showString "println"), doc (showString "("), prt 0 expr, doc (showString ")"), doc (showString ";")])
  prtList _ [] = (concatD [])
  prtList _ (x:xs) = (concatD [prt 0 x, prt 0 xs])
instance Print (Item a) where
  prt i e = case e of
    Init _ id expr -> prPrec i 0 (concatD [prt 0 id, doc (showString "="), prt 0 expr])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print (ElIfs a) where
  prt i e = case e of
    CondElIfs _ elif elifs -> prPrec i 0 (concatD [prt 0 elif, prt 0 elifs])
    NilElif _ -> prPrec i 0 (concatD [])

instance Print (ElIf a) where
  prt i e = case e of
    CondElIf _ expr stmts -> prPrec i 0 (concatD [doc (showString "elseif"), prt 0 expr, prt 0 stmts])

instance Print (List a) where
  prt i e = case e of
    Lis1 _ exprs -> prPrec i 0 (concatD [doc (showString "["), prt 0 exprs, doc (showString "]")])
    Lis2 _ expr1 expr2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 expr1, doc (showString ":"), prt 0 expr2, doc (showString "]")])
    Lis3 _ expr1 id expr2 expr3 -> prPrec i 0 (concatD [doc (showString "["), prt 0 expr1, doc (showString "for"), prt 0 id, doc (showString "in"), prt 0 expr2, doc (showString ":"), prt 0 expr3, doc (showString "]")])
    Lis4 _ expr id1 id2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 expr, doc (showString "for"), prt 0 id1, doc (showString "in"), prt 0 id2, doc (showString "]")])

instance Print (Expr a) where
  prt i e = case e of
    EVar _ id -> prPrec i 7 (concatD [prt 0 id])
    ELitInt _ n -> prPrec i 7 (concatD [prt 0 n])
    ELitLis _ list -> prPrec i 7 (concatD [prt 0 list])
    ELitTrue _ -> prPrec i 7 (concatD [doc (showString "True")])
    ELitFalse _ -> prPrec i 7 (concatD [doc (showString "False")])
    EApp _ id exprs -> prPrec i 7 (concatD [doc (showString "apply"), prt 0 id, doc (showString "("), prt 0 exprs, doc (showString ")")])
    EGen _ id -> prPrec i 7 (concatD [doc (showString "generator"), doc (showString "("), prt 0 id, doc (showString ")")])
    ETake _ id -> prPrec i 7 (concatD [doc (showString "take"), prt 0 id])
    ESlice _ id expr1 expr2 -> prPrec i 7 (concatD [prt 0 id, doc (showString "["), prt 0 expr1, doc (showString ":"), prt 0 expr2, doc (showString "]")])
    EAnon _ ids expr -> prPrec i 7 (concatD [doc (showString "{"), prt 0 ids, doc (showString "}"), doc (showString "->"), doc (showString "{"), prt 0 expr, doc (showString "}")])
    EString _ str -> prPrec i 7 (concatD [prt 0 str])
    EElem _ id expr -> prPrec i 6 (concatD [prt 0 id, doc (showString "["), prt 0 expr, doc (showString "]")])
    Neg _ expr -> prPrec i 6 (concatD [doc (showString "-"), prt 7 expr])
    Not _ expr -> prPrec i 6 (concatD [doc (showString "!"), prt 7 expr])
    Pow _ expr1 expr2 -> prPrec i 5 (concatD [prt 5 expr1, doc (showString "^"), prt 6 expr2])
    EMul _ expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "*"), prt 5 expr2])
    EDiv _ expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "/"), prt 5 expr2])
    EMod _ expr1 expr2 -> prPrec i 4 (concatD [prt 4 expr1, doc (showString "%"), prt 5 expr2])
    EAdd _ expr1 expr2 -> prPrec i 3 (concatD [prt 3 expr1, doc (showString "+"), prt 4 expr2])
    ESub _ expr1 expr2 -> prPrec i 3 (concatD [prt 3 expr1, doc (showString "-"), prt 4 expr2])
    ERel _ expr1 relop expr2 -> prPrec i 2 (concatD [prt 2 expr1, prt 0 relop, prt 3 expr2])
    EAnd _ expr1 expr2 -> prPrec i 1 (concatD [prt 2 expr1, doc (showString "&&"), prt 1 expr2])
    EOr _ expr1 expr2 -> prPrec i 0 (concatD [prt 1 expr1, doc (showString "||"), prt 0 expr2])
  prtList _ [] = (concatD [])
  prtList _ [x] = (concatD [prt 0 x])
  prtList _ (x:xs) = (concatD [prt 0 x, doc (showString ","), prt 0 xs])
instance Print (Asg a) where
  prt i e = case e of
    Eq _ -> prPrec i 0 (concatD [doc (showString "=")])
    PlEq _ -> prPrec i 0 (concatD [doc (showString "+=")])
    MnEq _ -> prPrec i 0 (concatD [doc (showString "-=")])
    MulEq _ -> prPrec i 0 (concatD [doc (showString "*=")])
    DivEq _ -> prPrec i 0 (concatD [doc (showString "/=")])
    PowEq _ -> prPrec i 0 (concatD [doc (showString "^=")])

instance Print (AddOp a) where
  prt i e = case e of
    Plus _ -> prPrec i 0 (concatD [doc (showString "+")])
    Minus _ -> prPrec i 0 (concatD [doc (showString "-")])

instance Print (MulOp a) where
  prt i e = case e of
    Times _ -> prPrec i 0 (concatD [doc (showString "*")])
    Div _ -> prPrec i 0 (concatD [doc (showString "/")])
    Mod _ -> prPrec i 0 (concatD [doc (showString "%")])

instance Print (RelOp a) where
  prt i e = case e of
    LTH _ -> prPrec i 0 (concatD [doc (showString "<")])
    LE _ -> prPrec i 0 (concatD [doc (showString "<=")])
    GTH _ -> prPrec i 0 (concatD [doc (showString ">")])
    GE _ -> prPrec i 0 (concatD [doc (showString ">=")])
    EQU _ -> prPrec i 0 (concatD [doc (showString "==")])
    NE _ -> prPrec i 0 (concatD [doc (showString "!=")])


